"Area: Migrations":
  - changed-files:
      - any-glob-to-any-file:
          - "app/api/mapping/migrations/*"
          - "app/api/files/migrations/*"
          - "app/api/jobs/migrations/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - "app/airflow/pyproject.toml"
          - "app/api/pyproject.toml"
          - "app/next-client-app/package-lock.json"
          - "app/next-client-app/package.json"

"Area: CI":
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

"Area: Backend":
  - changed-files:
      - any-glob-to-any-file: "app/api/**"

"Area: Frontend":
  - changed-files:
      - any-glob-to-any-file: "app/next-client-app/**"

"Area: Airflow":
  - changed-files:
      - any-glob-to-any-file: "app/airflow/**"
