name: test
permissions:
  contents: read

on: [pull_request]

jobs:
  test-django:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        django-version: ["4.2", "5"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: pip install uv

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        working-directory: app/api
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev,test]"

      - name: Install django ${{ matrix.django-version }}
        working-directory: app/api
        run: |
          source .venv/bin/activate
          uv pip install "Django==${{ matrix.django-version }}"

      - name: Test with Django
        env:
          SECRET_KEY: "test"
          ALLOWED_HOSTS: "['localhost']"
          DB_ENGINE: "django.db.backends.postgresql"
          DB_HOST: "localhost"
          DB_NAME: "test"
          DB_PASSWORD: "postgres"
          DB_PORT: "5432"
          DB_USER: "postgres"
          STORAGE_TYPE: "minio"
          MINIO_ENDPOINT: "minio:9000"
          MINIO_ACCESS_KEY: "minioadmin"
          MINIO_SECRET_KEY: "minioadmin" 
          
        working-directory: app/api
        run: |
          uv run pytest
